use crate::game::level::{LevelHub, PointHub};
use crate::prelude::*;
use moonshine_save::prelude::*;
use std::path::PathBuf;

pub fn save_world(path: impl Into<PathBuf>) -> SaveWorld {
    SaveWorld::default_into_file(path)
        .include_resource::<PointHub>()
        .include_resource::<LevelHub>()
        .exclude_component::<Mesh3d>()
        .exclude_component::<MeshMaterial3d<StandardMaterial>>()
        .exclude_component::<Name>()
        .exclude_component::<LinearVelocity>()
        .exclude_component::<AngularVelocity>()
        .exclude_component::<Collider>()
        .exclude_component::<RigidBody>()
        .exclude_component::<CollisionLayers>()
        .exclude_component::<CollisionEventsEnabled>()
        .exclude_component::<DebugRender>()
        .exclude_component::<Sensor>()
        .exclude_component::<Mass>()
        .exclude_component::<Restitution>()
        .exclude_component::<Friction>()
        .exclude_component::<SweptCcd>()
        .exclude_component::<MaxLinearSpeed>()
        .exclude_component::<SleepingDisabled>()
        .exclude_component::<ColliderOf>()
        .exclude_component::<RigidBodyColliders>()
        .exclude_component::<ColliderMassProperties>()
        .exclude_component::<ColliderDensity>()
        .exclude_component::<ColliderTransform>()
        .exclude_component::<ColliderAabb>()
        .exclude_component::<ColliderMarker>()
        .exclude_component::<ComputedMass>()
        .exclude_component::<ComputedAngularInertia>()
        .exclude_component::<ComputedCenterOfMass>()
        .exclude_component::<Sleeping>()
        .exclude_component::<SleepThreshold>()
        .exclude_component::<SleepTimer>()
        .exclude_component::<Position>()
        .exclude_component::<Rotation>()
        .exclude_component::<avian2d::collision::collider::EnlargedAabb>()
        .exclude_component::<avian2d::dynamics::integrator::VelocityIntegrationData>()
        .exclude_component::<avian2d::dynamics::rigid_body::forces::AccumulatedLocalAcceleration>()
        .exclude_component::<avian2d::dynamics::solver::solver_body::SolverBody>()
        .exclude_component::<avian2d::dynamics::solver::solver_body::SolverBodyInertia>()
        .exclude_component::<avian2d::physics_transform::PreSolveDeltaPosition>()
        .exclude_component::<avian2d::physics_transform::PreSolveDeltaRotation>()
        .exclude_component::<ChildOf>()
        .exclude_component::<Children>()
        .exclude_component::<GlobalTransform>()
        .exclude_component::<bevy::camera::visibility::ViewVisibility>()
        .exclude_component::<bevy::camera::visibility::InheritedVisibility>()
        .exclude_component::<bevy::camera::visibility::VisibilityClass>()
}
